# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75bc86eb3cfb77a20b3c4a2b3c582f4fec954ae7840e9bf4c7b92636c34d210e3f77c5018f534f09f05ac9135bfe5499af7a4faf251d483b963613c68ddd5421

test:
  secret_key_base: d5a681b5f5c65d2bf6d73d677b40310d224fec6301db684fd72910234b3bb99b61fe0f5d6ff6efb5f0a4ed5f3b37ec2a01c6e0a61bf0e490130a1c188ab32d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
